version: '3.8'

services:
  stock-collector:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: stock-collector:v2.0
    container_name: stock-data-collector
    restart: "no"
    volumes:
      # Mount the current folder (project root) to /app inside the container
      - .:/app
      # Mount the keys folder
      - ./docker/keys:/keys:ro
    environment:
      - GIT_EMAIL=docker@stock-in-ounces.local
      - GIT_NAME=Stock Updater Bot
      # Timezone for scheduling (change to your specific timezone if different)
      - TZ=America/Los_Angeles

